package com.zerochat.ui.discovery

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.zerochat.data.model.Peer
import com.zerochat.data.model.TransportMode
import com.zerochat.domain.PeerRepository
import com.zerochat.network.lan.LanPeer
import com.zerochat.network.lan.LanTransport
import com.zerochat.network.transport.TransportRouter
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch
import timber.log.Timber
import javax.inject.Inject

data class DiscoveryUiState(
    val peers: List<LanPeer> = emptyList(),
    val isDiscovering: Boolean = true,
    val error: String? = null,

    // ── PIN code ──────────────────────────────────────────────────
    /** The 8-digit code generated by this device for others to find */
    val myPinCode: String = "",
    /** Whether PIN code advertising is active */
    val isAdvertisingPin: Boolean = false,
    /** The PIN being looked up (user is typing) */
    val lookupPin: String = "",
    /** Whether PIN lookup is in progress */
    val isLookingUp: Boolean = false,
    /** Resolved peer from PIN lookup */
    val resolvedPeer: LanPeer? = null,
)

@HiltViewModel
class DiscoveryViewModel @Inject constructor(
    private val lanTransport: LanTransport,
    private val transportRouter: TransportRouter,
    private val peerRepository: PeerRepository,
) : ViewModel() {

    private val _uiState = MutableStateFlow(DiscoveryUiState())
    val uiState: StateFlow<DiscoveryUiState> = _uiState.asStateFlow()

    init {
        startDiscovery()
        observeDiscoveredPeers()
        generatePinCode()
    }

    // ── WiFi / mDNS Discovery ────────────────────────────────────

    fun startDiscovery() {
        viewModelScope.launch {
            _uiState.update { it.copy(isDiscovering = true, error = null) }
            try {
                lanTransport.startWiFiDirectDiscovery()
                lanTransport.startMdnsDiscovery()
            } catch (e: Exception) {
                _uiState.update { it.copy(error = e.message, isDiscovering = false) }
            }
        }
    }

    fun connectToPeer(peer: LanPeer) {
        viewModelScope.launch {
            try {
                val fingerprint = peer.deviceId.ifBlank { peer.ipAddress }
                transportRouter.connectLan(peer.ipAddress, peer.port, fingerprint)

                // Save peer to contacts so it appears in the contacts list
                savePeer(fingerprint, peer)

                Timber.i("Connected to peer $fingerprint via LAN")
            } catch (e: Exception) {
                _uiState.update { it.copy(error = "Connection failed: ${e.message}") }
            }
        }
    }

    fun connectManually(peerIdOrIp: String) {
        viewModelScope.launch {
            try {
                val ipPattern = Regex("\\d+\\.\\d+\\.\\d+\\.\\d+")
                if (ipPattern.matches(peerIdOrIp)) {
                    transportRouter.connectLan(peerIdOrIp, Peer.DEFAULT_PORT, peerIdOrIp)
                    Timber.i("Manual connection to $peerIdOrIp")
                } else {
                    _uiState.update { it.copy(error = "Peer ID resolution not yet implemented") }
                }
            } catch (e: Exception) {
                _uiState.update { it.copy(error = "Connection failed: ${e.message}") }
            }
        }
    }

    // ── PIN Code (8-digit) ───────────────────────────────────────

    /**
     * Generate a random 8-digit PIN and start advertising it via mDNS.
     * The PIN is embedded in the mDNS service name so other devices can
     * find this device by typing the PIN.
     */
    private fun generatePinCode() {
        val pin = lanTransport.getOrCreatePinCode()
        _uiState.update { it.copy(myPinCode = pin, isAdvertisingPin = true) }
    }

    /**
     * Start advertising this device's PIN code via mDNS.
     */
    fun startPinAdvertising() {
        viewModelScope.launch {
            try {
                lanTransport.advertisePinCode()
                _uiState.update { it.copy(isAdvertisingPin = true, error = null) }
            } catch (e: Exception) {
                _uiState.update { it.copy(error = "Failed to advertise: ${e.message}") }
            }
        }
    }

    /**
     * Lookup a PIN code — search mDNS for a device with this PIN.
     * When found, resolves to an IP address and connects.
     */
    fun lookupPinCode(pin: String) {
        if (pin.length != 8 || !pin.all { it.isDigit() }) {
            _uiState.update { it.copy(error = "PIN must be exactly 8 digits") }
            return
        }

        viewModelScope.launch {
            _uiState.update { it.copy(isLookingUp = true, error = null, resolvedPeer = null) }

            try {
                val peer = lanTransport.resolvePinCode(pin)
                if (peer != null) {
                    _uiState.update {
                        it.copy(
                            isLookingUp = false,
                            resolvedPeer = peer,
                            lookupPin = pin,
                        )
                    }
                    // Auto-connect
                    connectToPeer(peer)
                } else {
                    _uiState.update {
                        it.copy(
                            isLookingUp = false,
                            error = "No device found with PIN $pin. Make sure both devices are on the same WiFi network.",
                        )
                    }
                }
            } catch (e: Exception) {
                _uiState.update {
                    it.copy(
                        isLookingUp = false,
                        error = "PIN lookup failed: ${e.message}",
                    )
                }
            }
        }
    }

    fun updateLookupPin(pin: String) {
        _uiState.update { it.copy(lookupPin = pin.take(8).filter { it.isDigit() }, resolvedPeer = null) }
    }

    // ── Private ──────────────────────────────────────────────────

    /**
     * Save a discovered peer to the contacts database so it appears
     * in the ContactsScreen list without needing to re-discover.
     */
    private suspend fun savePeer(fingerprint: String, peer: LanPeer) {
        try {
            val existing = peerRepository.getPeer(fingerprint)
            if (existing == null) {
                val newPeer = Peer(
                    fingerprint = fingerprint,
                    displayName = peer.displayName.ifBlank { peer.ipAddress },
                    ipAddress = peer.ipAddress,
                    port = peer.port,
                    preferredTransport = TransportMode.LAN,
                    lastSeen = System.currentTimeMillis(),
                )
                peerRepository.savePeer(newPeer)
                Timber.i("Peer saved to contacts: $fingerprint")
            } else {
                // Update connection info for existing peer
                peerRepository.updateConnectionInfo(
                    fingerprint = fingerprint,
                    ipAddress = peer.ipAddress,
                    transport = "LAN",
                    timestamp = System.currentTimeMillis(),
                )
            }
        } catch (e: Exception) {
            Timber.w(e, "Failed to save peer $fingerprint")
        }
    }

    private fun observeDiscoveredPeers() {
        viewModelScope.launch {
            lanTransport.discoveredPeers().collect { peers ->
                _uiState.update {
                    it.copy(
                        peers = peers,
                        isDiscovering = false,
                    )
                }
            }
        }
    }
}
